command_timeout = 1000

#

format = """
[](4)\
$username\
[](bg:2 fg:4)\
$directory\
[](fg:2 bg:8)\
$git_branch\
$git_status\
[](fg:8 bg:14)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$php\
[](fg:14 bg:6)\
$docker_context\
[](fg:6 bg:7)\
$time\
[](fg:7)\
$line_break\
$character\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:4 fg:0 bold"
style_root = "bg:4 fg:9"
format = '[$user ]($style)'

[directory]
style = "bg:2 fg:0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[docker_context]
symbol = " "
style = "bg:6"
format = '[[ $symbol $context ](bg:6)]($style) $path'

[git_branch]
symbol = ""
style = "bg:8"
format = '[[ $symbol $branch ](bg:8)]($style)'

[git_status]
stashed = ""
style = "bg:8"
format = '[[($all_status$ahead_behind )](bg:8)]($style)'

[nodejs]
symbol = ""
style = "bg:14 fg:0"
format = '[[ $symbol ($version) ](bg:14)]($style)'

[php]
symbol = ""
style = "bg:14 fg:0"
format = '[[ $symbol ($version )](bg:14 fg:0)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:7 fg:0"
format = '[[ $time ](bg:7 fg:0)]($style)'

[line_break]
disabled = false
